// react/src/lib/ZxForm.tsx
import "../App.css";

import ZxInput from "./ZxInput.tsx";

import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../components/ui/card.tsx"

import { Button } from "../components/ui/button.tsx";

import { z, ZodType } from "zod"
import { useState } from "react";

export type FormProps = {
  schema: z.ZodObject<any>;
  action?: string,
  method?: string | undefined
};

export default function ZxForm({ schema, action = "", method = "GET" }: FormProps) {
  let meta = schema.meta()
  let data: any = useState({});

  function onsubmit(event) {
    if (meta?.preventDefault || meta?.callback) {
      event.preventDefault();
    }

    let result = schema.safeParse(data)

    if (typeof meta?.callback === "function") {
      meta.callback(result.data);
    }
  }

  return (<Card className="mx-auto w-full max-w-sm">
    <CardHeader>
      <CardTitle className="text-2xl">{meta?.title ?? "Form"}</CardTitle>
      <CardDescription>{meta?.description ?? ""}</CardDescription>
    </CardHeader>
    <CardContent>
      <form noValidate onSubmit={onsubmit} className="grid gap-4" action={action} method={method}>
        {Object.entries(schema.shape).map(entry => {
          return (<ZxInput key={entry[0]} input={entry as [string, ZodType]} data={entry[1]}></ZxInput>)
        })}
        <Button type="submit" className="w-full hover:cursor-pointer">Submit</Button>
      </form>
    </CardContent>
  </Card>)
}

// svelte/src/lib/ZxForm.svelte
<script lang="ts">
  import "./app.css";
  import { ZodType } from "zod";

  import * as Card from "./components/ui/card/index.js";
  import Button from "./components/ui/button/button.svelte";
  import ZxInput from "./ZxInput.svelte";

  import { type FormProps } from "./types.js";
  import { validate_callback } from "./validate-store.js";

  let {
    schema,
    action = "",
    method = "GET",
    // header,
    footer,
  }: FormProps = $props();

  let meta = schema.meta();
  let data: any = $state({});

  function onsubmit(event: SubmitEvent) {
    if (meta?.preventDefault || meta?.callback) {
      event.preventDefault();
    }

    validate_callback.update((value) => !value);
    let result = schema.safeParse(data);

    if (!result.success) {
      event.preventDefault();
      // TODO: Add in validate() on the inputs so that they turn red
      return;
    }

    if (typeof meta?.callback === "function") {
      meta.callback(result.data);
    }
  }
</script>

<Card.Root class="mx-auto w-full max-w-sm">
  <Card.Header>
    <Card.Title class="text-2xl">{meta?.title ?? "Form"}</Card.Title>
    <Card.Description>{meta?.description ?? ""}</Card.Description>
  </Card.Header>
  <Card.Content>
    <form novalidate {onsubmit} class="grid gap-4" {action} {method}>
      {#each Object.entries(schema.shape) as [key, value]}
        <ZxInput input={[key, value as ZodType<any, any>]} bind:data></ZxInput>
      {/each}

      <Button type="submit" class="w-full hover:cursor-pointer">{meta?.submitName ? meta?.submitName : "Submit"}</Button>
    </form>

    {@render footer?.()}
  </Card.Content>
</Card.Root>
